/**
 * GENERATED by `npm run levels:manifest` from src/levels/*.json — do not edit by hand.
 * `npm run levels:check` fails while this file is stale (a level was added, renamed or its star
 * clocks changed). Each `load` is a dynamic import so Vite emits one chunk per level (PERF-2);
 * only the metadata below ships in the eager bundle. See src/levels/index.ts for the API.
 */
import type { LevelDef } from '../sim/types';
import type { LevelTextTranslations } from '../ui/i18n';

/** JSON string fields are widened by TS; the validator (`npm run levels:check`) guards the enums. */
const def = (m: { default: unknown }): LevelDef => m.default as LevelDef;

/** Metadata per level; `name_az` / `name_ru` / `name_tr` are the translated names (I18N-2). */
export interface LevelManifestEntry extends Pick<LevelTextTranslations, 'name_az' | 'name_ru' | 'name_tr'> {
  readonly id: number;
  readonly name: string;
  /** Star clocks in ms (GDD §3): finish under `star3` for three stars, under `star2` for two. */
  readonly star3: number;
  readonly star2: number;
  readonly load: () => Promise<LevelDef>;
}

/** Every level in play order. */
export const LEVEL_MANIFEST: readonly LevelManifestEntry[] = [
  { id: 1, name: 'First Taps', name_az: 'İlk Toxunuş', name_ru: 'Первые тапы', name_tr: 'İlk Dokunuş', star3: 30000, star2: 60000, load: () => import('./001-first-taps.json').then(def) },
  { id: 2, name: 'Supply Line', name_az: 'Təchizat Xətti', name_ru: 'Снабжение', name_tr: 'İkmal Hattı', star3: 20000, star2: 75000, load: () => import('./002-supply-line.json').then(def) },
  { id: 3, name: 'Free Real Estate', name_az: 'Sahibsiz Torpaq', name_ru: 'Ничейная земля', name_tr: 'Bedava Arsa', star3: 25000, star2: 70000, load: () => import('./003-free-real-estate.json').then(def) },
  { id: 4, name: 'Build Up', name_az: 'Güc Topla', name_ru: 'Накопление', name_tr: 'Güç Topla', star3: 25000, star2: 135000, load: () => import('./004-build-up.json').then(def) },
  { id: 5, name: 'Around the Wall', name_az: 'Divarı Dolan', name_ru: 'Обойди стену', name_tr: 'Duvarı Dolaş', star3: 30000, star2: 80000, load: () => import('./005-two-roads.json').then(def) },
  { id: 6, name: 'Outpost First', name_az: 'Əvvəl Forpost', name_ru: 'Сначала форпост', name_tr: 'Önce Karakol', star3: 25000, star2: 100000, load: () => import('./006-outpost-first.json').then(def) },
  { id: 7, name: 'Long March', name_az: 'Uzun Yürüş', name_ru: 'Долгий марш', name_tr: 'Uzun Yürüyüş', star3: 25000, star2: 75000, load: () => import('./007-long-march.json').then(def) },
  { id: 8, name: 'Two Bases', name_az: 'İki Baza', name_ru: 'Две базы', name_tr: 'İki Üs', star3: 40000, star2: 90000, load: () => import('./008-two-bases.json').then(def) },
  { id: 9, name: 'Stone Walls', name_az: 'Daş Divarlar', name_ru: 'Каменные стены', name_tr: 'Taş Duvarlar', star3: 25000, star2: 50000, load: () => import('./009-stone-walls.json').then(def) },
  { id: 10, name: 'Hold the Line', name_az: 'Xətti Saxla', name_ru: 'Держи строй', name_tr: 'Hattı Tut', star3: 20000, star2: 50000, load: () => import('./010-hold-the-line.json').then(def) },
  { id: 11, name: 'Starve the Keep', name_az: 'Qalanı Ac Qoy', name_ru: 'Голодная осада', name_tr: 'Kaleyi Aç Bırak', star3: 30000, star2: 60000, load: () => import('./011-starve-the-keep.json').then(def) },
  { id: 12, name: 'Gun Post', name_az: 'Top Postu', name_ru: 'Батарея', name_tr: 'Top Mevzii', star3: 20000, star2: 40000, load: () => import('./012-gun-post.json').then(def) },
  { id: 13, name: 'Crossfire', name_az: 'Çarpaz Atəş', name_ru: 'Под огнём', name_tr: 'Çapraz Ateş', star3: 35000, star2: 70000, load: () => import('./013-crossfire.json').then(def) },
  { id: 14, name: 'Guns and Walls', name_az: 'Top və Divar', name_ru: 'Пушки и стены', name_tr: 'Toplar ve Surlar', star3: 25000, star2: 50000, load: () => import('./014-guns-and-walls.json').then(def) },
  { id: 15, name: 'The Citadel', name_az: 'Sitadel', name_ru: 'Цитадель', name_tr: 'İç Kale', star3: 35000, star2: 70000, load: () => import('./015-the-citadel.json').then(def) },
  { id: 16, name: 'Last Bastion', name_az: 'Son Bastion', name_ru: 'Последний оплот', name_tr: 'Son Kale', star3: 20000, star2: 40000, load: () => import('./016-last-bastion.json').then(def) },
  { id: 17, name: 'Minefield', name_az: 'Mina Sahəsi', name_ru: 'Минное поле', name_tr: 'Mayın Alanı', star3: 25000, star2: 50000, load: () => import('./017-minefield.json').then(def) },
  { id: 18, name: 'Two Rivals', name_az: 'İki Rəqib', name_ru: 'Два врага', name_tr: 'İki Rakip', star3: 30000, star2: 60000, load: () => import('./018-two-rivals.json').then(def) },
  { id: 19, name: 'Toll Gate', name_az: 'Keçid Haqqı', name_ru: 'Пошлина', name_tr: 'Paralı Kapı', star3: 25000, star2: 50000, load: () => import('./019-toll-road.json').then(def) },
  { id: 20, name: 'The Boulder', name_az: 'Qaya', name_ru: 'Валун', name_tr: 'Kaya', star3: 25000, star2: 50000, load: () => import('./020-roadblock.json').then(def) },
  { id: 21, name: 'Mined Flank', name_az: 'Minalı Cinah', name_ru: 'Минный фланг', name_tr: 'Mayınlı Kanat', star3: 25000, star2: 50000, load: () => import('./021-behind-the-wall.json').then(def) },
  { id: 22, name: 'Castle in the Middle', name_az: 'Ortadakı Qala', name_ru: 'Замок в центре', name_tr: 'Ortadaki Kale', star3: 35000, star2: 70000, load: () => import('./022-castle-in-the-middle.json').then(def) },
  { id: 23, name: 'First Blood', name_az: 'İlk Qan', name_ru: 'Первая кровь', name_tr: 'İlk Kan', star3: 30000, star2: 75000, load: () => import('./023-first-blood.json').then(def) },
  { id: 24, name: 'The Gauntlet', name_az: 'Sınaq Keçidi', name_ru: 'Сквозь строй', name_tr: 'Zorlu Geçit', star3: 30000, star2: 60000, load: () => import('./024-the-gauntlet.json').then(def) },
  { id: 25, name: 'Heavy Metal', name_az: 'Ağır Metal', name_ru: 'Тяжёлый металл', name_tr: 'Ağır Metal', star3: 20000, star2: 40000, load: () => import('./025-heavy-metal.json').then(def) },
  { id: 26, name: 'Steamroller', name_az: 'Buldozer', name_ru: 'Каток', name_tr: 'Silindir', star3: 25000, star2: 50000, load: () => import('./026-steamroller.json').then(def) },
  { id: 27, name: 'Armour Race', name_az: 'Zireh Yarışı', name_ru: 'Гонка брони', name_tr: 'Zırh Yarışı', star3: 40000, star2: 80000, load: () => import('./027-armour-race.json').then(def) },
  { id: 28, name: 'Hold the Ford', name_az: 'Keçidi Tut', name_ru: 'Держи брод', name_tr: 'Geçidi Tut', star3: 35000, star2: 70000, load: () => import('./028-burn-the-bridge.json').then(def) },
  { id: 29, name: 'Two Fords', name_az: 'İki Keçid', name_ru: 'Два брода', name_tr: 'İki Geçit', star3: 25000, star2: 50000, load: () => import('./029-island-hopping.json').then(def) },
  { id: 30, name: 'One Front', name_az: 'Bir Cəbhə', name_ru: 'Один фронт', name_tr: 'Tek Cephe', star3: 40000, star2: 80000, load: () => import('./030-drawbridge.json').then(def) },
  { id: 31, name: 'Guns over the River', name_az: 'Çay Üstü Toplar', name_ru: 'Пушки над рекой', name_tr: 'Nehir Üstü Toplar', star3: 30000, star2: 60000, load: () => import('./031-guns-over-the-river.json').then(def) },
  { id: 32, name: 'Siege Works', name_az: 'Mühasirə', name_ru: 'Осадные работы', name_tr: 'Kuşatma', star3: 40000, star2: 80000, load: () => import('./032-siege-works.json').then(def) },
  { id: 33, name: 'Three Kings', name_az: 'Üç Kral', name_ru: 'Три короля', name_tr: 'Üç Kral', star3: 35000, star2: 70000, load: () => import('./033-three-kings.json').then(def) },
  { id: 34, name: 'Weakest Link', name_az: 'Ən Zəif Halqa', name_ru: 'Слабое звено', name_tr: 'En Zayıf Halka', star3: 30000, star2: 60000, load: () => import('./034-weakest-link.json').then(def) },
  { id: 35, name: 'Powder Keg', name_az: 'Barıt Anbarı', name_ru: 'Бочка пороха', name_tr: 'Barut Fıçısı', star3: 25000, star2: 50000, load: () => import('./035-powder-keg.json').then(def) },
  { id: 36, name: 'One Wide Ford', name_az: 'Geniş Keçid', name_ru: 'Широкий брод', name_tr: 'Geniş Geçit', star3: 40000, star2: 80000, load: () => import('./036-three-bridges.json').then(def) },
  { id: 37, name: 'Tank Country', name_az: 'Tank Ölkəsi', name_ru: 'Страна танков', name_tr: 'Tank Ülkesi', star3: 55000, star2: 110000, load: () => import('./037-tank-country.json').then(def) },
  { id: 38, name: 'Ring of Fire', name_az: 'Atəş Halqası', name_ru: 'Кольцо огня', name_tr: 'Ateş Çemberi', star3: 25000, star2: 50000, load: () => import('./038-ring-of-fire.json').then(def) },
  { id: 39, name: 'The Long Night', name_az: 'Uzun Gecə', name_ru: 'Долгая ночь', name_tr: 'Uzun Gece', star3: 75000, star2: 150000, load: () => import('./039-the-long-night.json').then(def) },
  { id: 40, name: 'The Crown', name_az: 'Tac', name_ru: 'Корона', name_tr: 'Taç', star3: 50000, star2: 100000, load: () => import('./040-the-crown.json').then(def) },
  { id: 41, name: 'Twin Rivers', name_az: 'Əkiz Çaylar', name_ru: 'Две реки', name_tr: 'İkiz Nehirler', star3: 70000, star2: 140000, load: () => import('./041-twin-rivers.json').then(def) },
  { id: 42, name: 'Siege Engine', name_az: 'Mühasirə Maşını', name_ru: 'Осадная машина', name_tr: 'Kuşatma Aracı', star3: 60000, star2: 120000, load: () => import('./042-siege-engine.json').then(def) },
  { id: 43, name: 'Iron Convoy', name_az: 'Dəmir Karvan', name_ru: 'Стальной обоз', name_tr: 'Demir Konvoy', star3: 30000, star2: 60000, load: () => import('./043-iron-convoy.json').then(def) },
  { id: 44, name: 'Minefield Crossing', name_az: 'Mina Sahəsi Keçidi', name_ru: 'Через минное поле', name_tr: 'Mayın Tarlası Geçidi', star3: 25000, star2: 50000, load: () => import('./044-minefield-crossing.json').then(def) },
  { id: 45, name: 'Three Fronts', name_az: 'Üç Cəbhə', name_ru: 'Три фронта', name_tr: 'Üç Cephe', star3: 40000, star2: 80000, load: () => import('./045-three-fronts.json').then(def) },
  { id: 46, name: 'River Gate', name_az: 'Çay Qapısı', name_ru: 'Врата реки', name_tr: 'Nehir Kapısı', star3: 45000, star2: 90000, load: () => import('./046-the-long-bridge.json').then(def) },
  { id: 47, name: 'Scorched Earth', name_az: 'Yanmış Torpaq', name_ru: 'Выжженная земля', name_tr: 'Yakılmış Toprak', star3: 40000, star2: 90000, load: () => import('./047-scorched-earth.json').then(def) },
  { id: 48, name: 'Kings\' Council', name_az: 'Krallar Şurası', name_ru: 'Совет королей', name_tr: 'Krallar Meclisi', star3: 45000, star2: 90000, load: () => import('./048-kings-council.json').then(def) },
  { id: 49, name: 'Last Light', name_az: 'Son İşıq', name_ru: 'Свет в ночи', name_tr: 'Son Işık', star3: 25000, star2: 50000, load: () => import('./049-last-light.json').then(def) },
  { id: 50, name: 'The Crown Reforged', name_az: 'Yenidən Dövülmüş Tac', name_ru: 'Корона, отлитая вновь', name_tr: 'Yeniden Dövülen Taç', star3: 40000, star2: 90000, load: () => import('./050-the-crown-reforged.json').then(def) },
];
