/**
 * GENERATED by `npm run levels:manifest` from src/levels/*.json — do not edit by hand.
 * `npm run levels:check` fails while this file is stale (a level was added, renamed or its star
 * clocks changed). Each `load` is a dynamic import so Vite emits one chunk per level (PERF-2);
 * only the metadata below ships in the eager bundle. See src/levels/index.ts for the API.
 */
import type { LevelDef } from '../sim/types';

/** JSON string fields are widened by TS; the validator (`npm run levels:check`) guards the enums. */
const def = (m: { default: unknown }): LevelDef => m.default as LevelDef;

export interface LevelManifestEntry {
  readonly id: number;
  readonly name: string;
  /** Star clocks in ms (GDD §3): finish under `star3` for three stars, under `star2` for two. */
  readonly star3: number;
  readonly star2: number;
  readonly load: () => Promise<LevelDef>;
}

/** Every level in play order. */
export const LEVEL_MANIFEST: readonly LevelManifestEntry[] = [
  { id: 1, name: 'First Taps', star3: 30000, star2: 60000, load: () => import('./001-first-taps.json').then(def) },
  { id: 2, name: 'Supply Line', star3: 30000, star2: 60000, load: () => import('./002-supply-line.json').then(def) },
  { id: 3, name: 'Free Real Estate', star3: 30000, star2: 60000, load: () => import('./003-free-real-estate.json').then(def) },
  { id: 4, name: 'Build Up', star3: 40000, star2: 80000, load: () => import('./004-build-up.json').then(def) },
  { id: 5, name: 'Two Roads', star3: 30000, star2: 60000, load: () => import('./005-two-roads.json').then(def) },
  { id: 6, name: 'Outpost First', star3: 45000, star2: 90000, load: () => import('./006-outpost-first.json').then(def) },
  { id: 7, name: 'Long March', star3: 50000, star2: 100000, load: () => import('./007-long-march.json').then(def) },
  { id: 8, name: 'Two Bases', star3: 35000, star2: 70000, load: () => import('./008-two-bases.json').then(def) },
  { id: 9, name: 'Stone Walls', star3: 25000, star2: 50000, load: () => import('./009-stone-walls.json').then(def) },
  { id: 10, name: 'Hold the Line', star3: 65000, star2: 130000, load: () => import('./010-hold-the-line.json').then(def) },
  { id: 11, name: 'Starve the Keep', star3: 30000, star2: 60000, load: () => import('./011-starve-the-keep.json').then(def) },
  { id: 12, name: 'Gun Post', star3: 20000, star2: 40000, load: () => import('./012-gun-post.json').then(def) },
  { id: 13, name: 'Crossfire', star3: 55000, star2: 110000, load: () => import('./013-crossfire.json').then(def) },
  { id: 14, name: 'Guns and Walls', star3: 30000, star2: 60000, load: () => import('./014-guns-and-walls.json').then(def) },
  { id: 15, name: 'The Citadel', star3: 30000, star2: 60000, load: () => import('./015-the-citadel.json').then(def) },
  { id: 16, name: 'Last Bastion', star3: 30000, star2: 60000, load: () => import('./016-last-bastion.json').then(def) },
  { id: 17, name: 'Minefield', star3: 20000, star2: 40000, load: () => import('./017-minefield.json').then(def) },
  { id: 18, name: 'Two Rivals', star3: 45000, star2: 105000, load: () => import('./018-two-rivals.json').then(def) },
  { id: 19, name: 'Toll Road', star3: 30000, star2: 65000, load: () => import('./019-toll-road.json').then(def) },
  { id: 20, name: 'Roadblock', star3: 20000, star2: 50000, load: () => import('./020-roadblock.json').then(def) },
  { id: 21, name: 'Behind the Wall', star3: 25000, star2: 50000, load: () => import('./021-behind-the-wall.json').then(def) },
  { id: 22, name: 'Castle in the Middle', star3: 45000, star2: 90000, load: () => import('./022-castle-in-the-middle.json').then(def) },
  { id: 23, name: 'First Blood', star3: 45000, star2: 90000, load: () => import('./023-first-blood.json').then(def) },
  { id: 24, name: 'The Gauntlet', star3: 35000, star2: 70000, load: () => import('./024-the-gauntlet.json').then(def) },
  { id: 25, name: 'Heavy Metal', star3: 40000, star2: 80000, load: () => import('./025-heavy-metal.json').then(def) },
  { id: 26, name: 'Steamroller', star3: 25000, star2: 55000, load: () => import('./026-steamroller.json').then(def) },
  { id: 27, name: 'Armour Race', star3: 25000, star2: 50000, load: () => import('./027-armour-race.json').then(def) },
  { id: 28, name: 'Burn the Bridge', star3: 40000, star2: 80000, load: () => import('./028-burn-the-bridge.json').then(def) },
  { id: 29, name: 'Island Hopping', star3: 20000, star2: 40000, load: () => import('./029-island-hopping.json').then(def) },
  { id: 30, name: 'Drawbridge', star3: 20000, star2: 40000, load: () => import('./030-drawbridge.json').then(def) },
  { id: 31, name: 'Guns over the River', star3: 65000, star2: 130000, load: () => import('./031-guns-over-the-river.json').then(def) },
  { id: 32, name: 'Siege Works', star3: 25000, star2: 50000, load: () => import('./032-siege-works.json').then(def) },
  { id: 33, name: 'Three Kings', star3: 40000, star2: 80000, load: () => import('./033-three-kings.json').then(def) },
  { id: 34, name: 'Weakest Link', star3: 35000, star2: 70000, load: () => import('./034-weakest-link.json').then(def) },
  { id: 35, name: 'Powder Keg', star3: 20000, star2: 40000, load: () => import('./035-powder-keg.json').then(def) },
  { id: 36, name: 'Three Bridges', star3: 30000, star2: 60000, load: () => import('./036-three-bridges.json').then(def) },
  { id: 37, name: 'Tank Country', star3: 35000, star2: 70000, load: () => import('./037-tank-country.json').then(def) },
  { id: 38, name: 'Ring of Fire', star3: 25000, star2: 50000, load: () => import('./038-ring-of-fire.json').then(def) },
  { id: 39, name: 'The Long Night', star3: 40000, star2: 80000, load: () => import('./039-the-long-night.json').then(def) },
  { id: 40, name: 'The Crown', star3: 35000, star2: 70000, load: () => import('./040-the-crown.json').then(def) },
];
