/**
 * Level manifest generator (PERF-2). `src/levels/manifest.ts` is generated from `src/levels/*.json`
 * so the eager bundle only carries the per-level metadata (id, name, star clocks) and one dynamic
 * `import()` per level; the level bodies become their own chunks. Shared by `npm run levels:manifest`
 * (writes the file) and `npm run levels:check` (fails when the file is stale).
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const LEVELS_DIR = fileURLToPath(new URL('../../src/levels/', import.meta.url));
export const MANIFEST_PATH = fileURLToPath(new URL('../../src/levels/manifest.ts', import.meta.url));
export const LEVEL_FILE_RE = /^\d{3}-[a-z0-9-]+\.json$/;

export interface ManifestEntry {
  file: string;
  id: number;
  name: string;
  star3: number;
  star2: number;
}

/** Level JSON files in play order (the numeric file prefix), as `NNN-name.json`. */
export function levelFiles(dir = LEVELS_DIR): string[] {
  return readdirSync(dir)
    .filter((f) => LEVEL_FILE_RE.test(f))
    .sort();
}

/** The metadata every manifest entry carries; validation of the rest is `validateLevel`'s job. */
export function readEntries(dir = LEVELS_DIR): ManifestEntry[] {
  return levelFiles(dir).map((file) => {
    const raw = JSON.parse(readFileSync(new URL(file, `file://${dir}`), 'utf8')) as Record<string, unknown>;
    const pick = (key: 'id' | 'star3' | 'star2'): number => {
      const v = raw[key];
      if (typeof v !== 'number' || !Number.isFinite(v)) throw new Error(`${file}: "${key}" must be a finite number`);
      return v;
    };
    const name = raw.name;
    if (typeof name !== 'string' || name.length === 0) throw new Error(`${file}: "name" must be a non-empty string`);
    return { file, id: pick('id'), name, star3: pick('star3'), star2: pick('star2') };
  });
}

const quote = (s: string): string => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

/** Source text of `src/levels/manifest.ts` for the given entries. */
export function renderManifest(entries: readonly ManifestEntry[]): string {
  const lines = entries.map(
    (e) =>
      `  { id: ${e.id}, name: ${quote(e.name)}, star3: ${e.star3}, star2: ${e.star2}, load: () => import('./${e.file}').then(def) },`,
  );
  return [
    '/**',
    ' * GENERATED by `npm run levels:manifest` from src/levels/*.json — do not edit by hand.',
    ' * `npm run levels:check` fails while this file is stale (a level was added, renamed or its star',
    ' * clocks changed). Each `load` is a dynamic import so Vite emits one chunk per level (PERF-2);',
    ' * only the metadata below ships in the eager bundle. See src/levels/index.ts for the API.',
    ' */',
    "import type { LevelDef } from '../sim/types';",
    '',
    '/** JSON string fields are widened by TS; the validator (`npm run levels:check`) guards the enums. */',
    'const def = (m: { default: unknown }): LevelDef => m.default as LevelDef;',
    '',
    'export interface LevelManifestEntry {',
    '  readonly id: number;',
    '  readonly name: string;',
    '  /** Star clocks in ms (GDD §3): finish under `star3` for three stars, under `star2` for two. */',
    '  readonly star3: number;',
    '  readonly star2: number;',
    '  readonly load: () => Promise<LevelDef>;',
    '}',
    '',
    '/** Every level in play order. */',
    'export const LEVEL_MANIFEST: readonly LevelManifestEntry[] = [',
    ...lines,
    '];',
    '',
  ].join('\n');
}

/** Errors that make the checked-in manifest stale (empty = up to date). */
export function checkManifest(dir = LEVELS_DIR, path = MANIFEST_PATH): string[] {
  const expected = renderManifest(readEntries(dir));
  if (!existsSync(path)) return [`${path} is missing — run \`npm run levels:manifest\``];
  const actual = readFileSync(path, 'utf8');
  if (actual === expected) return [];
  const exp = expected.split('\n');
  const act = actual.split('\n');
  const at = exp.findIndex((line, i) => line !== act[i]);
  return [
    `src/levels/manifest.ts is stale (first difference at line ${at + 1}: expected ${JSON.stringify(exp[at] ?? '<eof>')}, ` +
      `found ${JSON.stringify(act[at] ?? '<eof>')}) — run \`npm run levels:manifest\``,
  ];
}
